### ISSUE TITLE
Show Database data on the site

### ISSUE THREAD

**Issue by samjam48** [fac18/week6-FHIN-got-db#33]
You need to load the information from the database onto the web page. You have managed to get it sent to the front end and arrive in the javascript.

You might want replicate how 'coda-squall' are doing it
https://github.com/fac18/week6-coda-squall/tree/master/public/js

You want to create a function such as `populateTable()` that will go through the array of row and make a HTML row of the data then append all the rows to a table in your HTML.
You will call this function and pass it the array of row data that you are receiving from the backend

**Comment by kin-au** [comment]
Refer to issue #33 
https://github.com/fac18/week6-FHIN-got-db/issues/38
